import type {Episode} from '../episode/schema';
import type {VisualPlan} from '../visual/schemas';
import type {AssetPlan} from '../assets/assetStrategySchema';
import type {HybridRenderReport,HybridRenderInput} from '../composition/hybridTypes';
import {resolveHybridLayouts} from '../composition/layoutResolver';
import type {FrameFeatures} from './frameSimilarity';
import {hashSimilarity,median} from './frameSimilarity';
import {distribution} from './layoutQa';
import {scoreVisualQa} from './qaScoring';
import {recommendationsFromWarnings} from './qaRecommendations';
import {VisualQaReportSchema,type InputFingerprints,type QaHistoryEntry,type QaWarning,type VisualQaReport} from './qaSchema';

export type QaStill={sceneId:string;path:string;features:FrameFeatures};
export type QaInput={episode:Episode;visualPlan:VisualPlan;assetPlan:AssetPlan;hybridReport?:HybridRenderReport;hybridInput?:HybridRenderInput;stills:QaStill[];phase1Stills?:QaStill[];fingerprints:InputFingerprints;sourcePaths:{episode:string;visualPlan:string;assetPlan:string;hybridReport?:string;stillsDirectory?:string;phase1StillsDirectory?:string};history?:QaHistoryEntry[];historyLimit?:number;priorReportStale?:boolean;createdAt?:string};
const warning=(code:string,severity:QaWarning['severity'],message:string,sceneIds:string[]=[]):QaWarning=>({code,severity,message,sceneIds});
const ratio=(n:number,d:number)=>d?n/d:0;
function durationSeconds(episode:Episode){return episode.scenes.reduce((sum,scene)=>sum+scene.durationSeconds,0);}
function mostCommon(counts:Record<string,number>){return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]??null;}
function sceneSignature(archetype:string,layout:string,strategy:string,assetKinds:string[],procedural:string[]){return[archetype,layout,strategy,[...assetKinds].sort().join('+')||'no-asset',[...procedural].sort().join('+')||'no-procedural'].join('|');}
function assetKindCounts(plan:AssetPlan){const result=new Map<string,string[]>();for(const sp of plan.scenePlans){const kinds=sp.recraftAssets.map((asset)=>asset.assetKind);result.set(sp.sceneId,[...new Set(kinds)].sort());}return result;}
function crossEpisode(history:QaHistoryEntry[],sceneSummaries:ReturnType<typeof makeSceneSummaries>,currentAssets:Record<string,number>,limit:number){const recent=[...history].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,limit);const notes:string[]=[];const reuse=new Map<string,string[]>();for(const entry of recent)for(const assetId of Object.keys(entry.assetSummary)){const ids=reuse.get(assetId)??[];ids.push(entry.episodeId);reuse.set(assetId,ids);}const assetReuse=Object.entries(currentAssets).flatMap(([assetId])=>{const episodeIds=reuse.get(assetId)??[];return episodeIds.length>=2?[{assetId,episodeCount:episodeIds.length+1,episodeIds:[...episodeIds]}]:[];});
  const hook=sceneSummaries.find((s)=>s.sceneId.toLowerCase()==='hook')?.structuralSignature??null;const ending=sceneSummaries.find((s)=>s.sceneId.toLowerCase()==='ending')?.structuralSignature??null;const openingRepeated=!!hook&&recent.slice(0,3).filter((entry)=>entry.hookSignature===hook).length>=2;const endingRepeated=!!ending&&recent.slice(0,3).filter((entry)=>entry.endingSignature===ending).length>=2;if(openingRepeated)notes.push('Opening composition repeated across at least two of the three most recent episodes.');if(endingRepeated)notes.push('Ending composition repeated across at least two of the three most recent episodes.');
  const pairs:{episodeId:string;currentSceneId:string;previousSceneHash:string;similarity:number}[]=[];for(const current of sceneSummaries)if(current.stillHash)for(const entry of recent)for(const [sceneId,hash] of Object.entries(entry.representativeStillHashes)){const similarity=hashSimilarity(current.stillHash,hash);if(similarity>=.94)pairs.push({episodeId:entry.episodeId,currentSceneId:current.sceneId,previousSceneHash:`${sceneId}:${hash}`,similarity});}
  return{comparedEpisodeIds:recent.map((entry)=>entry.episodeId),historyLimit:limit,metadataOnlyEpisodeIds:recent.filter((entry)=>Object.keys(entry.representativeStillHashes).length===0).map((entry)=>entry.episodeId),crossEpisodeHighSimilarityPairs:pairs.sort((a,b)=>b.similarity-a.similarity).slice(0,20),assetReuse,openingRepeated,endingRepeated,notes};}
function makeSceneSummaries(input:QaInput){const {episode,visualPlan,assetPlan,hybridInput,stills}=input;const hybridScenes=new Map((hybridInput?.scenes??[]).map((scene)=>[scene.sceneId,scene]));const layouts=hybridInput?Object.fromEntries(hybridInput.scenes.map((scene)=>[scene.sceneId,scene.layout])):resolveHybridLayouts(episode,visualPlan,assetPlan).layouts;const visualById=new Map(visualPlan.scenePlans.map((scene)=>[scene.sceneId,scene]));const assetById=new Map(assetPlan.scenePlans.map((scene)=>[scene.sceneId,scene]));const stillById=new Map(stills.map((still)=>[still.sceneId,still]));return episode.scenes.map((episodeScene)=>{const visual=visualById.get(episodeScene.id)!;const plan=assetById.get(episodeScene.id)!;const hybrid=hybridScenes.get(episodeScene.id);const still=stillById.get(episodeScene.id);const strategy=hybrid?.resolvedStrategy??plan.strategy;const assetKinds=[...new Set(plan.recraftAssets.map((asset)=>asset.assetKind))].sort();const assetIds=[...new Set([...(hybrid?.assetIds??[]),...plan.recraftAssets.map((asset)=>asset.libraryAssetId??asset.assetId)])].sort();const procedural=[...new Set(plan.proceduralElements)].sort();const illustrationDominant=hybrid?hybrid.resolvedStrategy==='recraft'&&hybrid.assetIds.length>0&&hybrid.fallbacks.length===0:plan.strategy==='recraft'&&plan.proceduralElements.length===0;return{sceneId:episodeScene.id,layout:layouts[episodeScene.id]??visual.layoutVariant,archetype:visual.primaryArchetype,strategy,assetKinds,assetIds,proceduralElements:procedural,structuralSignature:sceneSignature(visual.primaryArchetype,layouts[episodeScene.id]??visual.layoutVariant,strategy,assetKinds,procedural),illustrationDominant,textDominant:visual.textDominant,signatureMoment:hybrid?.signatureMoment??false,...(still?{stillPath:still.path,stillHash:still.features.hash,palette:{meanLuminance:still.features.meanLuminance,meanSaturation:still.features.meanSaturation,darkPixelRatio:still.features.darkPixelRatio,coarseHue:still.features.coarseHue}}:{})};});}
export function isVisualQaReportStale(report:Pick<VisualQaReport,'inputFingerprints'>,current:InputFingerprints){return JSON.stringify(report.inputFingerprints)!==JSON.stringify(current);}
export function buildVisualQa(input:QaInput):VisualQaReport{
  const scenes=makeSceneSummaries(input),warnings:QaWarning[]=[],sceneCount=scenes.length,duration=durationSeconds(input.episode);const layout=distribution(scenes.map((s)=>s.layout)),archetype=distribution(scenes.map((s)=>s.archetype));
  if(input.hybridReport&&(input.hybridReport.renderStatus==='DRAFT — UNREVIEWED ASSETS'||input.hybridReport.pendingAssetCount>0))warnings.push(warning('unreviewed-draft-assets','warning',`Hybrid render is a draft with ${input.hybridReport.pendingAssetCount} pending, unreviewed asset(s); human approval is still required.`));
  for(const message of input.hybridReport?.warnings??[])if(/opaque .*background|matte/i.test(message))warnings.push(warning('compositing-matte','warning',`Inspect the illustrated asset edge over the dark background: ${message}`));
  if(duration>=60&&layout.uniqueCount<3)warnings.push(warning('layout-diversity','warning',`Only ${layout.uniqueCount} distinct layouts appear across a ${duration.toFixed(1)} second episode.`,scenes.map((s)=>s.sceneId)));
  if(layout.longestRun>2){let best:string[]=[];for(let i=0;i<scenes.length;){let j=i+1;while(j<scenes.length&&scenes[j].layout===scenes[i].layout)j++;if(j-i>best.length)best=scenes.slice(i,j).map((s)=>s.sceneId);i=j;}warnings.push(warning('layout-run','warning',`A layout repeats for ${layout.longestRun} consecutive scenes.`,best));}
  if(layout.dominantRatio>=.75)warnings.push(warning('layout-dominance','critical',`One layout occupies ${Math.round(layout.dominantRatio*100)}% of scenes.`,scenes.filter((s)=>layout.counts[s.layout]===Math.max(...Object.values(layout.counts))).map((s)=>s.sceneId)));else if(layout.dominantRatio>.5)warnings.push(warning('layout-dominance','warning',`One layout occupies ${Math.round(layout.dominantRatio*100)}% of scenes.`,scenes.filter((s)=>layout.counts[s.layout]===Math.max(...Object.values(layout.counts))).map((s)=>s.sceneId)));
  if(duration>=60&&archetype.uniqueCount<3)warnings.push(warning('archetype-diversity','warning',`Only ${archetype.uniqueCount} primary archetypes appear across a ${duration.toFixed(1)} second episode.`));if(archetype.dominantRatio===1&&sceneCount>1)warnings.push(warning('archetype-dominance','critical','Every scene uses the same primary archetype.',scenes.map((s)=>s.sceneId)));else if(archetype.dominantRatio>.6)warnings.push(warning('archetype-dominance','warning',`One primary archetype occupies ${Math.round(archetype.dominantRatio*100)}% of scenes.`));
  const assetPlacements=new Map<string,string[]>();for(const sp of input.assetPlan.scenePlans)for(const asset of sp.recraftAssets){const id=asset.libraryAssetId??asset.assetId;assetPlacements.set(id,[...(assetPlacements.get(id)??[]),sp.sceneId]);}const totalAssetPlacements=[...assetPlacements.values()].reduce((sum,ids)=>sum+ids.length,0);const mostAsset=mostCommon(Object.fromEntries([...assetPlacements].map(([id,ids])=>[id,ids.length])));const stopwords=new Set(['motif','recurring','visual','same','with','from','that','this','into','along','stage','every','following','single','identical']);const motifTokens=input.visualPlan.persistentMotif.toLowerCase().split(/[^a-z0-9]+/).filter((word)=>word.length>3&&!stopwords.has(word)).map((word)=>word.endsWith('ways')?word.slice(0,-4):word.endsWith('s')?word.slice(0,-1):word);const motifMatches=(id:string)=>{const item=input.assetPlan.uniqueRecraftAssets.find((asset)=>asset.assetId===id||asset.libraryAssetId===id);const tokens=`${id} ${item?.subject??''} ${item?.reuseKey??''}`.toLowerCase().split(/[^a-z0-9]+/).filter((word)=>word.length>3).map((word)=>word.endsWith('way')?word.slice(0,-3):word.endsWith('s')?word.slice(0,-1):word);return motifTokens.some((token)=>tokens.includes(token));};const motifExemption=!!mostAsset&&mostAsset[1]>sceneCount*.5&&motifMatches(mostAsset[0]);const repetitionRatio=sceneCount?Math.max(0,...[...assetPlacements.values()].map((ids)=>ids.length))/sceneCount:0;if(repetitionRatio>.5&&!motifExemption)warnings.push(warning('asset-repetition','warning',`${mostAsset?.[0]??'One asset'} appears in ${mostAsset?.[1]??0}/${sceneCount} scenes.`,mostAsset?assetPlacements.get(mostAsset[0])??[]:[]));
  const illustrationCount=input.hybridReport?.illustrationDominantSceneCount??scenes.filter((s)=>s.illustrationDominant).length;const illustrationRatio=input.hybridReport?.illustrationDominantSceneRatio??ratio(illustrationCount,sceneCount);if(illustrationRatio>=.8)warnings.push(warning('illustration-dominance','critical',`Illustration-dominant scenes account for ${Math.round(illustrationRatio*100)}% of the episode.`,scenes.filter((s)=>s.illustrationDominant).map((s)=>s.sceneId)));else if(illustrationRatio>.6)warnings.push(warning('illustration-dominance','warning',`Illustration-dominant scenes account for ${Math.round(illustrationRatio*100)}% of the episode.`,scenes.filter((s)=>s.illustrationDominant).map((s)=>s.sceneId)));
  const productionMix:Record<string,number>={procedural:0,hybrid:0,illustrationDominant:0,reuse:0};for(const scene of scenes){const key=scene.illustrationDominant?'illustrationDominant':scene.strategy==='reuse'?'reuse':scene.strategy==='procedural'?'procedural':'hybrid';productionMix[key]++;}for(const key of Object.keys(productionMix))productionMix[key]=ratio(productionMix[key],sceneCount);
  const textDominantSceneRatio=ratio(scenes.filter((s)=>s.textDominant).length,sceneCount);if(textDominantSceneRatio>.6)warnings.push(warning('text-dominance','warning',`${Math.round(textDominantSceneRatio*100)}% of scenes are marked text-dominant.`,scenes.filter((s)=>s.textDominant).map((s)=>s.sceneId)));
  const structures=distribution(scenes.map((s)=>s.structuralSignature));const repeatedSceneIds=scenes.filter((s)=>structures.counts[s.structuralSignature]>1).map((s)=>s.sceneId);const sameStructCritical=structures.dominantRatio>=.75&&sceneCount>1;if(structures.longestRun>=3||structures.dominantRatio>.5)warnings.push(warning('structural-repetition',sameStructCritical?'critical':'warning',`Repeated scene structure reaches ${Math.round(structures.dominantRatio*100)}% of scenes; longest run is ${structures.longestRun}.`,repeatedSceneIds));
  const sortedStills=[...input.stills].sort((a,b)=>scenes.findIndex((s)=>s.sceneId===a.sceneId)-scenes.findIndex((s)=>s.sceneId===b.sceneId));const framePairs:{sceneA:string;sceneB:string;similarity:number;discountedTransition:boolean}[]=[];for(let i=0;i<sortedStills.length;i++)for(let j=i+1;j<sortedStills.length;j++){const a=sortedStills[i],b=sortedStills[j];const similarity=hashSimilarity(a.features.hash,b.features.hash);const idxA=scenes.findIndex((s)=>s.sceneId===a.sceneId),idxB=scenes.findIndex((s)=>s.sceneId===b.sceneId),adjacent=Math.abs(idxA-idxB)<=1;framePairs.push({sceneA:a.sceneId,sceneB:b.sceneId,similarity,discountedTransition:adjacent});}const weighted=framePairs.map((p)=>p.similarity*(p.discountedTransition?.75:1));const averageSimilarity=weighted.length?weighted.reduce((s,v)=>s+v,0)/weighted.length:null;const sortedPairs=[...framePairs].sort((a,b)=>b.similarity-a.similarity);const highPairs=framePairs.filter((p)=>p.similarity>=.94&&(!p.discountedTransition||p.similarity>=.985)).sort((a,b)=>b.similarity-a.similarity).slice(0,20);for(const pair of highPairs)warnings.push(warning('frame-repetition','warning',`Representative frames for ${pair.sceneA} and ${pair.sceneB} are highly similar (${Math.round(pair.similarity*100)}% dHash similarity).`,[pair.sceneA,pair.sceneB]));
  const luminances=scenes.flatMap((s)=>s.palette?[s.palette.meanLuminance]:[]),saturations=scenes.flatMap((s)=>s.palette?[s.palette.meanSaturation]:[]),medianLum=median(luminances),medianSat=median(saturations);const signatureScene=scenes.find((s)=>s.signatureMoment)??null;const driftCandidates=scenes.flatMap((s)=>{if(!s.palette||medianLum===null||medianSat===null)return[];const drift=Math.abs(s.palette.meanLuminance-medianLum)>.22||Math.abs(s.palette.meanSaturation-medianSat)>.3;return drift&&!s.signatureMoment?[{sceneId:s.sceneId,luminance:s.palette.meanLuminance,saturation:s.palette.meanSaturation,signatureExempt:false}]:[];});if(driftCandidates.length)warnings.push(warning('palette-drift','warning','One or more non-signature scenes differ substantially from the episode palette median.',driftCandidates.map((d)=>d.sceneId)));const darkCompatibility=luminances.length?(medianLum!<.4?'dark editorial baseline broadly fits; review relative outliers':'episode median is brighter than the intended dark editorial baseline; inspect the stills'):'not evaluated (no decodable PNG stills)';
  const neighbors=signatureScene?scenes.filter((s,i)=>Math.abs(i-scenes.indexOf(signatureScene))===1):[];const sigLayout=!!signatureScene&&neighbors.some((s)=>s.layout!==signatureScene.layout);const sigArch=!!signatureScene&&neighbors.some((s)=>s.archetype!==signatureScene.archetype);const sigFrame=signatureScene?(()=>{const sig=sortedStills.find((s)=>s.sceneId===signatureScene.sceneId);if(!sig)return null;const next=neighbors.map((s)=>sortedStills.find((frame)=>frame.sceneId===s.sceneId)).filter((v):v is QaStill=>!!v);return next.length>0&&next.every((s)=>hashSimilarity(sig.features.hash,s.features.hash)<.94);})():null;const signatureDistinctive=signatureScene?sigLayout||sigArch||sigFrame===true:null;if(!signatureScene||input.hybridReport?.signatureMomentRendered===false)warnings.push(warning('signature-not-rendered','warning','No rendered signature moment is marked for this Episode.'));else if(signatureDistinctive===false)warnings.push(warning('signature-not-distinctive','warning','Signature moment may not be visually distinctive.',[signatureScene.sceneId,...neighbors.map((s)=>s.sceneId)]));
  const limit=Math.max(1,Math.min(20,input.historyLimit??5));const cross=crossEpisode(input.history??[],scenes,Object.fromEntries([...assetPlacements].map(([id,ids])=>[id,ids.length])),limit);if(cross.openingRepeated)warnings.push(warning('opening-repeated','critical','Opening composition repeats across recent episodes.',['hook']));if(cross.endingRepeated)warnings.push(warning('ending-repeated','warning','Ending composition repeats across recent episodes.',['ending']));if(cross.assetReuse.length)for(const item of cross.assetReuse)if(item.episodeCount>=3)warnings.push(warning('cross-episode-asset-reuse','warning',`${item.assetId} appears in at least three of the latest episodes: ${item.episodeIds.join(', ')}.`));
  if(input.priorReportStale)warnings.push(warning('stale-report','info','The previous Visual QA report inputs changed; this run replaces that stale assessment.'));
  const summaryByScene:Record<string,string>={};for(const scene of scenes)summaryByScene[scene.sceneId]=scene.layout;const assetByScene:Record<string,string[]>={};for(const scene of scenes)assetByScene[scene.sceneId]=scene.assetKinds;
  const recommendations=recommendationsFromWarnings(warnings,summaryByScene,assetByScene);const hasWarnings=warnings.some((w)=>w.severity==='warning'||w.severity==='critical');const scores=scoreVisualQa({layout:layout.uniqueCount>=4?100:layout.uniqueCount===3?85:layout.uniqueCount===2?65:30,archetype:archetype.uniqueCount>=5?100:archetype.uniqueCount>=3?85:archetype.uniqueCount===2?65:30,frame:highPairs.length===0?100:Math.max(0,100-highPairs.length*20),structure:structures.dominantRatio>=.75?20:structures.dominantRatio>.5?55:structures.longestRun>=3?70:100,palette:driftCandidates.length?Math.max(40,100-driftCandidates.length*20):100,assetReuse:repetitionRatio>.5&&!motifExemption?65:100,illustration:illustrationRatio>=.8?20:illustrationRatio>.6?60:100,signature:signatureDistinctive===false?40:signatureDistinctive===true?100:75,criticalFail:sameStructCritical||illustrationRatio>=.8||layout.dominantRatio>=.75||archetype.dominantRatio===1&&sceneCount>1,hasWarnings});
  const phaseFrames=(input.phase1Stills??[]).flatMap((old)=>{const current=sortedStills.find((candidate)=>candidate.sceneId===old.sceneId);return current?[{sceneId:old.sceneId,phase1Path:old.path,hybridPath:current.path,similarity:hashSimilarity(old.features.hash,current.features.hash)}]:[];});const phase1Comparison=phaseFrames.length?{pairedFrames:phaseFrames.length,averageSimilarity:phaseFrames.reduce((sum,pair)=>sum+pair.similarity,0)/phaseFrames.length,pairs:phaseFrames,note:'Matched Phase 1 and hybrid render stills are compared only for structural pixel-feature differences. The comparison does not judge which version is more attractive.'}:null;
  const report=VisualQaReportSchema.parse({schemaVersion:'visual-qa-v1',episodeId:input.episode.id,createdAt:input.createdAt??new Date().toISOString(),methodology:'heuristic editorial QA; deterministic local metrics, not scientific or AI visual understanding',stale:false,priorReportStale:input.priorReportStale??false,inputFingerprints:input.fingerprints,sourcePaths:input.sourcePaths,phase1Comparison,withinEpisode:{sceneCount,durationSeconds:duration,layouts:{uniqueLayoutCount:layout.uniqueCount,longestRepeatedLayoutRun:layout.longestRun,dominantLayoutRatio:layout.dominantRatio,counts:layout.counts},archetypes:{uniqueArchetypes:archetype.uniqueCount,longestRepeatedArchetypeRun:archetype.longestRun,dominantArchetypeRatio:archetype.dominantRatio,counts:archetype.counts},assetRepetition:{uniqueAssets:assetPlacements.size,totalPlacements:totalAssetPlacements,mostUsedAsset:mostAsset?.[0]??null,mostUsedCount:mostAsset?.[1]??0,repetitionRatio,persistentMotifExemption:motifExemption},illustrationDominance:{sceneCount:illustrationCount,ratio:illustrationRatio,productionMix},frameSimilarity:{method:'64-bit dHash from deterministic PNG luminance samples',availableFrames:sortedStills.length,comparedPairs:framePairs.length,averageSimilarity,mostSimilarPair:sortedPairs[0]??null,highSimilarityPairs:highPairs,note:'Similarity is a visual repetition signal only. Adjacent scenes are discounted in the average and require a stronger threshold to warn.'},palette:{episodeMedianLuminance:medianLum,episodeMedianSaturation:medianSat,driftCandidates,darkCompatibility},textDominantSceneRatio,structuralRepetition:{uniqueSignatures:structures.uniqueCount,longestRepeatedRun:structures.longestRun,dominantRatio:structures.dominantRatio,repeatedSceneIds},signatureDistinctiveness:{sceneId:signatureScene?.sceneId??null,layoutDifferentFromNeighbors:sigLayout,archetypeDifferentFromNeighbors:sigArch,frameDistinctFromNeighbors:sigFrame??false,distinctive:signatureDistinctive},scenes},crossEpisode:cross,scores,warnings,recommendations,status:scores.status,gate:{result:scores.status,releaseModeAction:scores.status==='fail'?'stop':scores.status==='warning'?'human-review-required':'continue'}});
  return report;
}
export function historyEntryFromReport(report:VisualQaReport,reportPath:string):QaHistoryEntry{const scenes=report.withinEpisode.scenes,assets:Record<string,number>={};for(const scene of scenes)for(const id of scene.assetIds)assets[id]=(assets[id]??0)+1;const stills:Record<string,string>={};for(const scene of scenes)if(scene.stillHash)stills[scene.sceneId]=scene.stillHash;return{episodeId:report.episodeId,timestamp:report.createdAt,score:report.scores.total,reportPath,representativeStillHashes:stills,layoutSummary:report.withinEpisode.layouts.counts,archetypeSummary:report.withinEpisode.archetypes.counts,assetSummary:assets,sceneStructures:scenes.map((s)=>({sceneId:s.sceneId,structuralSignature:s.structuralSignature,assetIds:s.assetIds,...(s.stillHash?{stillHash:s.stillHash}:{})})),hookSignature:scenes.find((s)=>s.sceneId.toLowerCase()==='hook')?.structuralSignature??null,endingSignature:scenes.find((s)=>s.sceneId.toLowerCase()==='ending')?.structuralSignature??null,inputFingerprints:report.inputFingerprints};}
