import type {Episode} from '../episode/schema';
import type {AssetPlan} from '../assets/assetStrategySchema';
import type {VisualPlan} from '../visual/schemas';
import {HybridLayoutSchema,type HybridLayout} from './hybridTypes';

const ORDER:HybridLayout[]=['subject-left','subject-right','split-focus','corner-anchor','center-stage','full-field'];
const ARCHETYPE_LAYOUT:Record<string,HybridLayout>={agents:'subject-left',object_world:'subject-right',physical_system:'split-focus',data_curve:'corner-anchor',scale_comparison:'split-focus',network:'full-field',geometric:'full-field',probability:'center-stage',process_flow:'subject-left',field_wave:'center-stage',timeline_archive:'corner-anchor',spatial_map:'full-field'};
function inferSpatialLayout(spatial:string|undefined,archetype:string):HybridLayout {const value=spatial?.toLowerCase()??'';if(/corner/.test(value))return'corner-anchor';if(/split/.test(value))return'split-focus';if(/full.?field/.test(value))return'full-field';if(/left/.test(value))return'subject-left';if(/right/.test(value))return'subject-right';if(/center|central/.test(value))return'center-stage';return ARCHETYPE_LAYOUT[archetype]??'center-stage';}
export function resolveSignatureSceneId(visualPlan:VisualPlan):string {const terms=visualPlan.signatureMoment.toLowerCase().split(/[^a-z0-9]+/).filter((term)=>term.length>3);let winner=visualPlan.scenePlans[Math.floor(visualPlan.scenePlans.length/2)]?.sceneId??'';let best=-1;for(const scene of visualPlan.scenePlans){const text=`${scene.visualSubject} ${scene.motionIdea} ${scene.spatialLayout}`.toLowerCase();const score=terms.reduce((total,term)=>total+Number(text.includes(term)),0);if(score>best){best=score;winner=scene.sceneId;}}return winner;}
export function resolveHybridLayouts(episode:Episode,visualPlan:VisualPlan,_assetPlan:AssetPlan):{layouts:Record<string,HybridLayout>;signatureSceneId:string;warnings:string[]}{const signatureSceneId=resolveSignatureSceneId(visualPlan);const layouts:Record<string,HybridLayout>={};const warnings:string[]=[];let previous:HybridLayout[]=[];for(const scene of episode.scenes){const plan=visualPlan.scenePlans.find((item)=>item.sceneId===scene.id)!;let candidate=scene.id===signatureSceneId?'split-focus':inferSpatialLayout(plan.spatialLayout,plan.primaryArchetype);if(scene.id!==signatureSceneId&&previous.length>=2&&previous[0]===candidate&&previous[1]===candidate){candidate=ORDER.find((item)=>item!==candidate&&item!==previous[0])??'center-stage';}layouts[scene.id]=HybridLayoutSchema.parse(candidate);previous=[...previous.slice(-1),candidate];}for(let i=2;i<episode.scenes.length;i++){const a=layouts[episode.scenes[i-2].id];if(a===layouts[episode.scenes[i-1].id]&&a===layouts[episode.scenes[i].id])warnings.push(`Layout ${a} repeats for more than two consecutive scenes.`);}return{layouts,signatureSceneId,warnings};}
