import type {AssetPlan} from '../assets/assetStrategySchema';
import type {AssetGenerationManifest} from '../assets/generation/assetGenerationSchema';
import type {Episode} from '../episode/schema';
import type {VisualPlan} from '../visual/schemas';
import {HybridRenderInputSchema,type HybridInputScene,type HybridRenderInput,type HybridRenderReport} from './hybridTypes';
import {resolveHybridLayouts,resolveSignatureSceneId} from './layoutResolver';
import {resolveAndStageAssets} from './assetResolver';

export async function createHybridProductionContext(input:{root:string;episode:Episode;visualPlan:VisualPlan;assetPlan:AssetPlan;manifest:AssetGenerationManifest;reviewFile:string;allowPendingAssets:boolean}){
  if(input.assetPlan.episodeId!==input.episode.id||input.manifest.episodeId!==input.episode.id)throw new Error('Episode, AssetPlan, and Asset Manifest IDs must match.');
  const ids=input.episode.scenes.map((scene)=>scene.id);for(const [name,scenes] of [['VisualPlan',input.visualPlan.scenePlans],['AssetPlan',input.assetPlan.scenePlans]] as const)if(scenes.length!==ids.length||scenes.some((scene,index)=>scene.sceneId!==ids[index]))throw new Error(`${name} scenes must match Episode IDs and order.`);
  const {layouts,signatureSceneId,warnings:layoutWarnings}=resolveHybridLayouts(input.episode,input.visualPlan,input.assetPlan);const resolution=await resolveAndStageAssets({...input,layouts});const planById=new Map(input.visualPlan.scenePlans.map((scene)=>[scene.sceneId,scene]));const assetsByScene=resolution.sceneAssets;const fallbacksByScene=new Map<string,typeof resolution.fallbacks>();for(const fallback of resolution.fallbacks)fallbacksByScene.set(fallback.sceneId,[...(fallbacksByScene.get(fallback.sceneId)??[]),fallback]);
  const scenes:HybridInputScene[]=input.episode.scenes.map((scene)=>{const visual=planById.get(scene.id)!;const plan=input.assetPlan.scenePlans.find((item)=>item.sceneId===scene.id)!;const rendered=assetsByScene[scene.id]??[];const resolved=rendered.length===0?'procedural':plan.strategy==='reuse'?'reuse':plan.strategy==='recraft'&&plan.proceduralElements.length===0?'recraft':'hybrid';return{sceneId:scene.id,strategy:plan.strategy,resolvedStrategy:resolved,layout:layouts[scene.id],signatureMoment:scene.id===signatureSceneId,visualIntent:{primaryArchetype:visual.primaryArchetype,spatialLayout:visual.spatialLayout,cameraIntent:visual.cameraIntent,visualSubject:visual.visualSubject,motionIdea:visual.motionIdea},assetIds:rendered.map((asset)=>asset.assetId),fallbacks:fallbacksByScene.get(scene.id)??[]};});
  const snapshot:HybridRenderInput=HybridRenderInputSchema.parse({schemaVersion:'hybrid-render-input-v1',episodeId:input.episode.id,allowPendingAssets:input.allowPendingAssets,reviewDecisions:resolution.reviewState.assets.map(({assetId,decision})=>({assetId,decision})).sort((a,b)=>a.assetId.localeCompare(b.assetId)),scenes,stagedAssets:resolution.stagedAssets.sort((a,b)=>a.assetId.localeCompare(b.assetId))});
  const layoutsCount:Record<string,number>={};for(const scene of scenes)layoutsCount[scene.layout]=(layoutsCount[scene.layout]??0)+1;const illustrationDominantSceneCount=scenes.filter((scene)=>scene.assetIds.length>0&&scene.resolvedStrategy==='recraft'&&scene.fallbacks.length===0).length;const total=scenes.length;const signatureMomentRendered=scenes.some((scene)=>scene.sceneId===signatureSceneId);const reportBase={episodeId:input.episode.id,sceneCount:total,proceduralSceneCount:scenes.filter((s)=>s.resolvedStrategy==='procedural').length,hybridSceneCount:scenes.filter((s)=>s.resolvedStrategy==='hybrid').length,recraftSceneCount:scenes.filter((s)=>s.resolvedStrategy==='recraft').length,reuseSceneCount:scenes.filter((s)=>s.resolvedStrategy==='reuse').length,approvedAssetCount:resolution.counts.approved,pendingAssetCount:resolution.counts.pending,rejectedAssetCount:resolution.counts.rejected,fallbackCount:resolution.fallbacks.length,fallbacks:resolution.fallbacks,layoutCounts:layoutsCount,illustrationDominantSceneCount,illustrationDominantSceneRatio:total?illustrationDominantSceneCount/total:0,signatureMomentRendered,stagedAssetCount:resolution.stagedAssets.length,renderStatus:input.allowPendingAssets&&resolution.counts.pending>0?'DRAFT — UNREVIEWED ASSETS' as const:'rendered' as const,outputPath:null,warnings:[...resolution.warnings,...layoutWarnings,...(!assetsByScene[signatureSceneId]?.length?['Signature scene rendered with its procedural composition because no eligible illustration was staged.']:[])]};
  return{snapshot,reportBase:reportBase as Omit<HybridRenderReport,'renderStatus'|'outputPath'> & {renderStatus:HybridRenderReport['renderStatus'];outputPath:string|null},resolution,layouts,signatureSceneId,scenes};
}
