import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp, mkdir, readFile, rm, writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {deflateSync} from 'node:zlib';
import {generateAssets} from '../src/assets/generation/assetGenerator';
import {makeAssetCacheKey} from '../src/assets/generation/assetCache';
import {buildAssetPrompt,toRecraftRequest} from '../src/assets/generation/assetPromptBuilder';
import {mapSemanticRequestToProviderRequest} from '../src/recraft/RecraftProvider';
import {loadAssetRegistry} from '../src/assets/assetRegistry';
import {inspectPng} from '../src/assets/generation/assetValidator';
import {RecraftProviderError} from '../src/recraft/errors';
import type {AssetPlan, RecraftAssetBrief} from '../src/assets/assetStrategySchema';

const rootProject=process.cwd();
function crc32(buf:Buffer){let c=0xffffffff;for(const byte of buf){c^=byte;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function png(width=2,height=1,colorType=6){const channels=({0:1,2:3,3:1,4:2,6:4} as Record<number,number>)[colorType];const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(width,0);ihdr.writeUInt32BE(height,4);ihdr[8]=8;ihdr[9]=colorType;const row=Buffer.alloc(1+width*channels);row[0]=0;for(let i=1;i<row.length;i++)row[i]=i*13;const chunk=(type:string,data:Buffer)=>{const name=Buffer.from(type);const size=Buffer.alloc(4);size.writeUInt32BE(data.length);const crc=Buffer.alloc(4);crc.writeUInt32BE(crc32(Buffer.concat([name,data])));return Buffer.concat([size,name,data,crc]);};return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(row)),chunk('IEND',Buffer.alloc(0))]);}
function asset(id:string, risk:'low'|'medium'|'high'='low'):RecraftAssetBrief{return{assetId:id,assetKind:'object',subject:`A single abstract physical object ${id}.`,composition:'One isolated object with clear separation.',viewpoint:'Three-quarter view',isolation:'isolated',reuseKey:`reuse-${id}`,semanticRisk:risk,avoidConcepts:[],source:'new'};}
function plan(assets:RecraftAssetBrief[],episodeId='test-episode'):AssetPlan{return{episodeId,profileVersion:'recraft-v1',styleStatus:'locked',budget:{episodeDurationSeconds:60,recommendedMin:2,recommendedMax:4,hardMax:5,uniqueNewAssetCount:assets.length,utilization:assets.length/5},scenePlans:[{sceneId:'scene-1',strategy:assets.length?'hybrid':'reuse',reason:'An illustrated object paired with a procedural information relationship.',recraftAssets:assets,proceduralElements:['chart'],fallback:'procedural',requiresNewAsset:assets.length>0}],uniqueRecraftAssets:assets,reuseGroups:assets.map((a)=>({reuseKey:a.reuseKey,assetId:a.assetId,sceneIds:['scene-1'],source:'new'})),warnings:[]};}
async function setup(){const root=await mkdtemp(path.join(os.tmpdir(),'asset-generation-'));await mkdir(path.join(root,'prompts'),{recursive:true});await writeFile(path.join(root,'prompts','recraft-style-v1.md'),await readFile(path.join(rootProject,'prompts','recraft-style-v1.md')));return root;}
function fakeProvider(fn:(request:unknown)=>Promise<{bytes:Buffer;mimeType:'image/png';prompt:string;model:'recraftv3'}>){return{generateImage:fn as never};}
test('1 dry-run makes zero API calls and does not require Recraft configuration',async()=>{const root=await setup();try{const r=await generateAssets(plan([asset('one')]),{root,dryRun:true});assert.equal(r.recraftCalls,0);assert.equal(r.generate,1);assert.equal(r.dryRun,true);}finally{await rm(root,{recursive:true,force:true});}});
test('2 generation success writes a valid PNG',async()=>{const root=await setup();try{let calls=0;const r=await generateAssets(plan([asset('one')]),{root,provider:fakeProvider(async()=>{calls++;return{bytes:png(),mimeType:'image/png',prompt:'brief',model:'recraftv3'};})});assert.equal(calls,1);assert.equal(r.report?.newGenerationCount,1);assert.ok((await readFile(path.join(root,'assets/generated/test-episode/one.png'))).length>0);}finally{await rm(root,{recursive:true,force:true});}});
test('3 generation writes a manifest with review and background truth',async()=>{const root=await setup();try{await generateAssets(plan([asset('one')]),{root,provider:fakeProvider(async()=>({bytes:png(),mimeType:'image/png',prompt:'brief',model:'recraftv3'}))});const m=JSON.parse(await readFile(path.join(root,'assets/generated/test-episode/asset-manifest.json'),'utf8'));assert.equal(m.assets[0].status,'needs-human-review');assert.equal(m.assets[0].backgroundMode,'generated');}finally{await rm(root,{recursive:true,force:true});}});
test('4 second execution gets a cache hit with zero extra API calls',async()=>{const root=await setup();try{let calls=0;const provider=fakeProvider(async()=>{calls++;return{bytes:png(),mimeType:'image/png',prompt:'brief',model:'recraftv3'};});await generateAssets(plan([asset('one')]),{root,provider});const second=await generateAssets(plan([asset('one')]),{root,provider});assert.equal(calls,1);assert.equal(second.report?.cacheHitCount,1);assert.equal(second.report?.recraftCallCount,0);}finally{await rm(root,{recursive:true,force:true});}});
test('5 reuse resolves a registry asset created by an earlier episode',async()=>{const root=await setup();try{const provider=fakeProvider(async()=>({bytes:png(),mimeType:'image/png',prompt:'brief',model:'recraftv3'}));await generateAssets(plan([asset('one')],'first-episode'),{root,provider});const old=asset('one');old.source='registry';const second=plan([],'second-episode');second.scenePlans[0].recraftAssets=[old];const r=await generateAssets(second,{root});assert.equal(r.report?.reuseCount,1);assert.equal(r.report?.failureCount,0);}finally{await rm(root,{recursive:true,force:true});}});
test('6 missing reuse target fails without silently generating',async()=>{const root=await setup();try{const old=asset('missing');old.source='registry';const p=plan([]);p.scenePlans[0].recraftAssets=[old];let calls=0;const r=await generateAssets(p,{root,provider:fakeProvider(async()=>{calls++;throw Error('unexpected');})});assert.equal(calls,0);assert.equal(r.report?.failureCount,1);assert.match(r.report?.warnings[0]??'',/Reuse requested but asset not found/);}finally{await rm(root,{recursive:true,force:true});}});
test('7 high-risk assets are skipped by default',async()=>{const root=await setup();try{let calls=0;const r=await generateAssets(plan([asset('risk','high')]),{root,provider:fakeProvider(async()=>{calls++;return{bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'};})});assert.equal(calls,0);assert.equal(r.report?.skippedHighRiskCount,1);assert.equal(r.report?.fallbackRequired,true);}finally{await rm(root,{recursive:true,force:true});}});
test('8 explicit allow-high-risk permits generation',async()=>{const root=await setup();try{let calls=0;const r=await generateAssets(plan([asset('risk','high')]),{root,allowHighRisk:true,provider:fakeProvider(async()=>{calls++;return{bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'};})});assert.equal(calls,1);assert.equal(r.report?.skippedHighRiskCount,0);}finally{await rm(root,{recursive:true,force:true});}});
test('9 branching diagrams are defensively rejected',async()=>{const root=await setup();try{const a=asset('branch');a.subject='A precise branching diagram with several connected options';let calls=0;await assert.rejects(()=>generateAssets(plan([a]),{root,provider:fakeProvider(async()=>{calls++;throw Error();})}),/procedural-only/);assert.equal(calls,0);}finally{await rm(root,{recursive:true,force:true});}});
test('10 hard budget violation fails before any API call',async()=>{const root=await setup();try{const p=plan([asset('one'),asset('two')]);p.budget.hardMax=1;let calls=0;await assert.rejects(()=>generateAssets(p,{root,provider:fakeProvider(async()=>{calls++;throw Error();})}),/Budget violation.*Recraft calls made: 0/);assert.equal(calls,0);}finally{await rm(root,{recursive:true,force:true});}});
test('11 partial failure preserves assets that already succeeded',async()=>{const root=await setup();try{const p=plan([asset('one'),asset('two')]);let calls=0;const r=await generateAssets(p,{root,provider:fakeProvider(async()=>{calls++;if(calls===2)throw new RecraftProviderError('provider unavailable',{code:'HTTP_ERROR',statusCode:400});return{bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'};})});assert.equal(r.report?.successCount,1);assert.equal(r.report?.failureCount,1);assert.ok(await readFile(path.join(root,'assets/generated/test-episode/one.png')));assert.equal(await readFile(path.join(root,'assets/generated/test-episode/two.png')).then(()=>true,()=>false),false);}finally{await rm(root,{recursive:true,force:true});}});
test('12 retry-failed retries only the previously failed asset',async()=>{const root=await setup();try{const p=plan([asset('one'),asset('two')]);let calls=0;await generateAssets(p,{root,provider:fakeProvider(async()=>{calls++;if(calls===2)throw new RecraftProviderError('rejected',{code:'HTTP_ERROR',statusCode:400});return{bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'};})});let retryCalls=0;const r=await generateAssets(p,{root,retryFailed:true,provider:fakeProvider(async()=>{retryCalls++;return{bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'};})});assert.equal(retryCalls,1);assert.equal(r.report?.newGenerationCount,1);assert.equal(r.report?.failureCount,0);}finally{await rm(root,{recursive:true,force:true});}});
test('13 force regenerates while preserving the previous shared cache',async()=>{const root=await setup();try{let calls=0;const provider=fakeProvider(async()=>{calls++;return{bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'};});await generateAssets(plan([asset('one')]),{root,provider});const files=(await import('node:fs/promises')).readdir;const cacheRoot=path.join(root,'assets/cache/recraft/reuse-one');const before=await readFile(path.join(cacheRoot,(await files(cacheRoot))[0]));await generateAssets(plan([asset('one')]),{root,force:true,provider});assert.equal(calls,2);assert.deepEqual(await readFile(path.join(cacheRoot,(await files(cacheRoot))[0])),before);}finally{await rm(root,{recursive:true,force:true});}});
test('14 invalid PNG is rejected and reported failed',async()=>{const root=await setup();try{const r=await generateAssets(plan([asset('one')]),{root,provider:fakeProvider(async()=>({bytes:Buffer.from('not png'),mimeType:'image/png',prompt:'x',model:'recraftv3'}))});assert.equal(r.report?.failureCount,1);assert.equal(await readFile(path.join(root,'assets/generated/test-episode/one.png')).then(()=>true,()=>false),false);}finally{await rm(root,{recursive:true,force:true});}});
test('15 image width and height are detected',()=>{assert.deepEqual(inspectPng(png(2,1)),{width:2,height:1,hasAlpha:true,format:'png'});});
test('16 alpha status is derived from PNG color type',()=>{assert.equal(inspectPng(png(2,1,2)).hasAlpha,false);assert.equal(inspectPng(png(2,1,6)).hasAlpha,true);});
test('17 provider failure does not expose raw API secrets in reports',async()=>{const root=await setup();try{const secret='unit-test-api-secret';const r=await generateAssets(plan([asset('one')]),{root,provider:fakeProvider(async()=>{throw new Error(`Bearer ${secret}`);})});const serialized=JSON.stringify(r.report);assert.equal(serialized.includes(secret),false);}finally{await rm(root,{recursive:true,force:true});}});
test('18 Style ID is never serialized to manifest or report',async()=>{const root=await setup();try{const secret='test-style-secret-marker';const p=plan([asset('one')]);const r=await generateAssets(p,{root,provider:fakeProvider(async()=>({bytes:png(),mimeType:'image/png',prompt:`style ${secret}`,model:'recraftv3'}))});const text=JSON.stringify(r.report)+await readFile(path.join(root,'assets/generated/test-episode/asset-manifest.json'),'utf8');assert.equal(text.includes(secret),false);}finally{await rm(root,{recursive:true,force:true});}});
test('19 cache hash is deterministic and changes with semantic prompt',()=>{const args={reuseKey:'door-v1',profileVersion:'recraft-v1',prompt:'one door',assetKind:'architecture',composition:'isolated'};assert.equal(makeAssetCacheKey(args),makeAssetCacheKey(args));assert.notEqual(makeAssetCacheKey(args),makeAssetCacheKey({...args,prompt:'two doors'}));});
test('20 Episode-like plan input remains unchanged after generation',async()=>{const root=await setup();try{const p=plan([asset('one')]);const before=structuredClone(p);await generateAssets(p,{root,dryRun:true});assert.deepEqual(p,before);}finally{await rm(root,{recursive:true,force:true});}});
test('21 network retry is bounded and succeeds on the third attempt',async()=>{const root=await setup();try{let calls=0;const r=await generateAssets(plan([asset('one')]),{root,wait:async()=>{},provider:fakeProvider(async()=>{calls++;if(calls<3)throw new RecraftProviderError('network unavailable',{code:'NETWORK_ERROR'});return{bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'};})});assert.equal(calls,3);assert.equal(r.report?.recraftCallCount,3);}finally{await rm(root,{recursive:true,force:true});}});
test('22 non-retryable API errors are safely reported without retry',async()=>{const root=await setup();try{let calls=0;const r=await generateAssets(plan([asset('one')]),{root,provider:fakeProvider(async()=>{calls++;throw new RecraftProviderError('rejected',{code:'HTTP_ERROR',statusCode:400});})});assert.equal(calls,1);assert.equal(r.report?.failureCount,1);}finally{await rm(root,{recursive:true,force:true});}});
test('23 generated prompts remain within Recraft 1000-character limit',async()=>{const root=await setup();try{const a=asset('one');const prompt=await buildAssetPrompt(a,root);const request=mapSemanticRequestToProviderRequest(toRecraftRequest(a,prompt),'not-serialized-test-style');assert.ok(prompt.length<=950);assert.ok(request.prompt.length<=1000);}finally{await rm(root,{recursive:true,force:true});}});
test('24 generation writes a registry consumable by Task002 planning',async()=>{const root=await setup();try{await generateAssets(plan([asset('one')]),{root,provider:fakeProvider(async()=>({bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'}))});const registry=await loadAssetRegistry(root);assert.equal(registry.assets.length,1);assert.equal(registry.assets[0].reuseKey,'reuse-one');}finally{await rm(root,{recursive:true,force:true});}});
test('25 corrupt episode and shared cache PNGs are rejected before reuse',async()=>{const root=await setup();try{let calls=0;const provider=fakeProvider(async()=>{calls++;return{bytes:png(),mimeType:'image/png',prompt:'x',model:'recraftv3'};});const p=plan([asset('one')]);await generateAssets(p,{root,provider});const cacheDir=path.join(root,'assets/cache/recraft/reuse-one');const cacheName=(await (await import('node:fs/promises')).readdir(cacheDir))[0];await writeFile(path.join(cacheDir,cacheName),Buffer.from('bad cache'));await writeFile(path.join(root,'assets/generated/test-episode/one.png'),Buffer.from('bad episode image'));const result=await generateAssets(p,{root,provider});assert.equal(calls,2);assert.equal(result.report?.newGenerationCount,1);assert.ok((await readFile(path.join(root,'assets/generated/test-episode/one.png'))).length>0);}finally{await rm(root,{recursive:true,force:true});}});
