import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {deflateSync} from 'node:zlib';
import {EpisodeSchema} from '../src/episode/schema';
import {AssetPlanSchema} from '../src/assets/assetStrategySchema';
import {AssetGenerationManifestSchema} from '../src/assets/generation/assetGenerationSchema';
import {AssetReviewStateSchema,HybridRenderInputSchema} from '../src/composition/hybridTypes';
import {createHybridProductionContext} from '../src/composition/productionContext';
import {resolveHybridLayouts} from '../src/composition/layoutResolver';

const rootProject=process.cwd();
function crc32(buf:Buffer){let c=0xffffffff;for(const byte of buf){c^=byte;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function png(colorType=6){const channels=colorType===6?4:3;const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(1,0);ihdr.writeUInt32BE(1,4);ihdr[8]=8;ihdr[9]=colorType;const chunk=(type:string,data:Buffer)=>{const name=Buffer.from(type);const size=Buffer.alloc(4);size.writeUInt32BE(data.length);const crc=Buffer.alloc(4);crc.writeUInt32BE(crc32(Buffer.concat([name,data])));return Buffer.concat([size,name,data,crc]);};return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(Buffer.from([0,...Array.from({length:channels},(_,i)=>80+i)]))),chunk('IEND',Buffer.alloc(0))]);}
function inputFixtures(options:{decision?:'approved'|'rejected'|'pending';kind?:'object'|'character';alpha?:boolean;missing?:boolean}={}){const episode=EpisodeSchema.parse({schemaVersion:1,id:'hybrid-test-episode',title:'A Test Episode',fps:30,width:1920,height:1080,scenes:[{id:'scene-one',durationSeconds:2,type:'hook',content:{eyebrow:'TEST',headline:'More can be worse.',emphasis:'worse',question:'Why?',participants:['One','Two']}}],networks:{}});const kind=options.kind??'object';const visualPlan={episodeArchetype:'object_world',persistentMotif:'A restrained repeated object motif.',signatureMoment:'A single illuminated object reveals the change.',scenePlans:[{sceneId:'scene-one',primaryArchetype:'object_world',visualSubject:'One isolated object.',motionIdea:'The object slowly emerges.',cameraIntent:'slow_push_in',spatialLayout:'Subject left of center with negative space on the right.',continuityFromPrevious:'Opening.',reuseExistingPrimitive:'None.',requiredCapabilities:[],layoutVariant:'left-focus',textDominant:false}],preferredExternalAsset:'none'};const assetPlan=AssetPlanSchema.parse({episodeId:episode.id,profileVersion:'recraft-v1',styleStatus:'locked',budget:{episodeDurationSeconds:2,recommendedMin:0,recommendedMax:1,hardMax:1,uniqueNewAssetCount:1,utilization:1},scenePlans:[{sceneId:'scene-one',strategy:'hybrid',reason:'One object with procedural labels.',recraftAssets:[{assetId:'test-asset',assetKind:kind,subject:'One simple test subject.',composition:'Isolated.',isolation:'isolated',reuseKey:'test-reuse',semanticRisk:'low',avoidConcepts:[],source:'new'}],proceduralElements:['highlight-path'],fallback:'procedural',requiresNewAsset:true}],uniqueRecraftAssets:[],reuseGroups:[],warnings:[]});const manifest=AssetGenerationManifestSchema.parse({schemaVersion:'asset-generation-manifest-v1',episodeId:episode.id,assets:[{id:'test-asset',reuseKey:'test-reuse',assetKind:kind,subject:'One simple test subject.',episodeId:episode.id,sceneIds:['scene-one'],provider:'recraft',profileVersion:'recraft-v1',promptVersion:'recraft-style-v1',prompt:'NO EMBEDDED TEXT. Test prompt.',cacheKey:'a'.repeat(64),filePath:`assets/generated/${episode.id}/test.png`,width:1,height:1,format:'png',hasAlpha:options.alpha??true,backgroundMode:'generated',createdAt:'2026-01-01T00:00:00.000Z',semanticRisk:'low',status:'needs-human-review',warnings:[]}]});return{episode,visualPlan,assetPlan,manifest};}
async function setup(options:Parameters<typeof inputFixtures>[0]={}){const root=await mkdtemp(path.join(os.tmpdir(),'hybrid-composer-'));const fixture=inputFixtures(options);if(!options.missing){const source=path.join(root,fixture.manifest.assets[0].filePath);await mkdir(path.dirname(source),{recursive:true});await writeFile(source,png(options.alpha===false?2:6));}const reviewFile=path.join(root,'assets/generated',fixture.episode.id,'asset-review.json');if(options.decision){await mkdir(path.dirname(reviewFile),{recursive:true});await writeFile(reviewFile,JSON.stringify(AssetReviewStateSchema.parse({episodeId:fixture.episode.id,assets:[{assetId:'test-asset',decision:options.decision,notes:'test',reviewedAt:'2026-01-01T00:00:00.000Z'}]})));}return{root,fixture,reviewFile};}
const resolve=async(s:Awaited<ReturnType<typeof setup>>,allowPendingAssets=false)=>createHybridProductionContext({root:s.root,...s.fixture,reviewFile:s.reviewFile,allowPendingAssets});

test('hybrid resolver uses only approved assets in the safe render',async()=>{const s=await setup({decision:'approved'});try{const context=await resolve(s);assert.equal(context.resolution.sceneAssets['scene-one'].length,1);assert.equal(context.reportBase.approvedAssetCount,1);}finally{await rm(s.root,{recursive:true,force:true});}});
test('pending assets fall back by default and can enter a clearly marked draft',async()=>{const s=await setup();try{const safe=await resolve(s);assert.equal(safe.resolution.sceneAssets['scene-one'],undefined);assert.equal(safe.resolution.fallbacks[0].decision,'pending');assert.equal(safe.reportBase.renderStatus,'rendered');const draft=await resolve(s,true);assert.equal(draft.resolution.sceneAssets['scene-one'].length,1);assert.equal(draft.reportBase.renderStatus,'DRAFT — UNREVIEWED ASSETS');}finally{await rm(s.root,{recursive:true,force:true});}});
test('rejected assets never bypass review and rejected characters fall back to AgentToken',async()=>{const s=await setup({decision:'rejected',kind:'character'});try{const context=await resolve(s,true);assert.equal(context.resolution.sceneAssets['scene-one'],undefined);assert.equal(context.resolution.fallbacks[0].fallbackKind,'agent-token');assert.equal(context.snapshot.scenes[0].assetIds.length,0);}finally{await rm(s.root,{recursive:true,force:true});}});
test('missing source asset is reported and resolves to procedural fallback',async()=>{const s=await setup({decision:'approved',missing:true});try{const context=await resolve(s);assert.equal(context.resolution.stagedAssets.length,0);assert.match(context.resolution.fallbacks[0].reason,/missing or invalid/);}finally{await rm(s.root,{recursive:true,force:true});}});
test('corrupt source PNG resolves to procedural fallback without aborting composition',async()=>{const s=await setup({decision:'approved'});try{await writeFile(path.join(s.root,s.fixture.manifest.assets[0].filePath),Buffer.from('not-a-png'));const context=await resolve(s);assert.equal(context.resolution.stagedAssets.length,0);assert.match(context.resolution.fallbacks[0].reason,/missing or invalid/);}finally{await rm(s.root,{recursive:true,force:true});}});
test('invalid review state fails closed instead of silently approving assets',async()=>{const s=await setup({decision:'approved'});try{await writeFile(s.reviewFile,'{"episodeId":"wrong","assets":[]}');await assert.rejects(()=>resolve(s),/episodeId does not match|Invalid asset review state/);}finally{await rm(s.root,{recursive:true,force:true});}});
test('alpha state is retained for transparent and opaque staged images',async()=>{for(const alpha of [true,false]){const s=await setup({decision:'approved',alpha});try{const context=await resolve(s);assert.equal(context.resolution.stagedAssets[0].hasAlpha,alpha);}finally{await rm(s.root,{recursive:true,force:true});}}});
test('staging is deterministic and never changes the source asset',async()=>{const s=await setup({decision:'approved'});try{const source=path.join(s.root,s.fixture.manifest.assets[0].filePath);const before=createHash('sha256').update(await readFile(source)).digest('hex');const first=await resolve(s);const firstSnapshot=JSON.stringify(first.snapshot);const staged=path.join(s.root,'public',first.resolution.stagedAssets[0].publicPath);const stagedHash=createHash('sha256').update(await readFile(staged)).digest('hex');const second=await resolve(s);assert.equal(JSON.stringify(second.snapshot),firstSnapshot);assert.equal(stagedHash,second.resolution.stagedAssets[0].sha256);assert.equal(createHash('sha256').update(await readFile(source)).digest('hex'),before);}finally{await rm(s.root,{recursive:true,force:true});}});
test('reuse keeps the same staged asset path and hash across scene references',async()=>{const s=await setup({decision:'approved'});try{const p=s.fixture.assetPlan;p.scenePlans.push({...p.scenePlans[0],sceneId:'scene-two'});p.scenePlans[0].recraftAssets[0].source='new';p.scenePlans[1].sceneId='scene-two';const v=s.fixture.visualPlan;v.scenePlans.push({...v.scenePlans[0],sceneId:'scene-two'});s.fixture.episode.scenes.push({...s.fixture.episode.scenes[0],id:'scene-two'});const context=await resolve(s);assert.equal(context.resolution.stagedAssets.length,1);assert.equal(context.resolution.sceneAssets['scene-one'][0].publicPath,context.resolution.sceneAssets['scene-two'][0].publicPath);}finally{await rm(s.root,{recursive:true,force:true});}});
test('layout resolution is deterministic and limits repeated layouts to two',()=>{const fixture=inputFixtures({});const plan=fixture.visualPlan;plan.scenePlans=[0,1,2,3,4].map((i)=>({...plan.scenePlans[0],sceneId:`scene-${i}`,spatialLayout:'center stage'}));const episode={...fixture.episode,scenes:plan.scenePlans.map((item)=>({...fixture.episode.scenes[0],id:item.sceneId}))};const a=resolveHybridLayouts(episode as never,plan as never,fixture.assetPlan);const b=resolveHybridLayouts(episode as never,plan as never,fixture.assetPlan);assert.deepEqual(a.layouts,b.layouts);for(let i=2;i<5;i++){const recent=[a.layouts[`scene-${i-2}`],a.layouts[`scene-${i-1}`],a.layouts[`scene-${i}`]];assert.ok(!(recent[0]===recent[1]&&recent[1]===recent[2]));}});
test('signature scene is rendered as a distinct composition when its asset is eligible',async()=>{const s=await setup({decision:'approved'});try{const context=await resolve(s);assert.equal(context.snapshot.scenes[0].signatureMoment,true);assert.equal(context.reportBase.signatureMomentRendered,true);assert.equal(context.snapshot.scenes[0].layout,'split-focus');}finally{await rm(s.root,{recursive:true,force:true});}});
test('hybrid overlays preserve procedural information elements and avoid illustration-dominant overclaim',async()=>{const s=await setup({decision:'approved'});try{const context=await resolve(s);assert.equal(context.snapshot.scenes[0].resolvedStrategy,'hybrid');assert.equal(context.reportBase.illustrationDominantSceneRatio,0);}finally{await rm(s.root,{recursive:true,force:true});}});
test('dominant ratio counts only pure illustration-led scenes',async()=>{const s=await setup({decision:'approved'});try{const plan=s.fixture.assetPlan;plan.scenePlans[0].strategy='recraft';plan.scenePlans[0].proceduralElements=[];const context=await resolve(s);assert.equal(context.reportBase.recraftSceneCount,1);assert.equal(context.reportBase.illustrationDominantSceneCount,1);assert.equal(context.reportBase.illustrationDominantSceneRatio,1);}finally{await rm(s.root,{recursive:true,force:true});}});
test('hybrid snapshots are deterministic, schema-valid, and contain no secret fields',async()=>{const s=await setup({decision:'approved'});try{const context=await resolve(s);assert.doesNotThrow(()=>HybridRenderInputSchema.parse(context.snapshot));const serialized=JSON.stringify(context.snapshot)+JSON.stringify(context.reportBase);for(const secret of ['RECRAFT_API_KEY','RECRAFT_STYLE_ID','Authorization','api_key'])assert.equal(serialized.includes(secret),false);}finally{await rm(s.root,{recursive:true,force:true});}});
test('hybrid composition has no provider call path and leaves Phase 1 props optional',async()=>{const s=await setup({decision:'approved'});const oldFetch=globalThis.fetch;let calls=0;globalThis.fetch=(async()=>{calls++;throw new Error('network access is forbidden in this test');}) as typeof fetch;try{await resolve(s);assert.equal(calls,0);assert.match(await readFile(path.join(rootProject,'src/compositions/EpisodeVideo.tsx'),'utf8'),/hybridSceneAssets\?/);}finally{globalThis.fetch=oldFetch;await rm(s.root,{recursive:true,force:true});}});
