import test from 'node:test';
import assert from 'node:assert/strict';
import braess from '../../episodes/braess-paradox.json';
import auction from '../../episodes/dollar-auction.json';
import { normalizeEpisode } from './normalizeEpisode';
import { validateEpisode } from './validateEpisode';
const copy = () => JSON.parse(JSON.stringify(braess));
test('both examples normalize to their actual timeline durations', () => { assert.equal(normalizeEpisode(braess).durationInFrames, 1800); assert.equal(normalizeEpisode(auction).durationInFrames, 1422); });
test('missing title reports filename, path and missing value', () => { const e = copy(); delete e.title; assert.throws(() => validateEpisode(e, 'broken.json'), /broken.json:[\s\S]*title:[\s\S]*received missing/); });
test('unknown scene type fails at scene discriminator', () => { const e = copy(); e.scenes[0].type = 'unknown'; assert.throws(() => validateEpisode(e), /scenes\[0\].type/); });
test('negative duration fails before rendering', () => { const e = copy(); e.scenes[0].durationSeconds = -1; assert.throws(() => validateEpisode(e), /scenes\[0\].durationSeconds/); });
test('missing network reference has precise location', () => { const e = copy(); e.scenes[0].content.networkId = 'missing'; assert.throws(() => validateEpisode(e), /scenes\[0\].content.networkId: expected existing reference/); });
test('duplicate scene IDs rejected', () => { const e = copy(); e.scenes[1].id = e.scenes[0].id; assert.throws(() => validateEpisode(e), /duplicate/); });
test('unsupported version is explicit', () => { const e = copy(); e.schemaVersion = 2; assert.throws(() => validateEpisode(e), /Unsupported schema version; expected 1, received 2/); });
test('unknown styling fields are rejected', () => { const e = copy(); e.scenes[0].content.style = { color: 'red' }; assert.throws(() => validateEpisode(e), /Unrecognized key/); });
test('rounded durations and overlaps use the same fps rule', () => { const e = copy(); e.scenes = e.scenes.slice(0, 2); e.scenes[0].durationSeconds = 2.015; e.scenes[1].durationSeconds = 3.025; e.scenes[1].transition = { overlapSeconds: .115 }; const n = normalizeEpisode(e); assert.equal(n.durationInFrames, 60 + 91 - 3); });
test('zero-frame scenes and excessive adjacent overlaps fail', () => { const e = copy(); e.scenes[0].durationSeconds = .001; assert.throws(() => validateEpisode(e), /at least one frame/); e.scenes[0].durationSeconds = 1; e.scenes[1].transition = { overlapSeconds: 1 }; assert.throws(() => validateEpisode(e), /shorter than both/); });
test('invalid node and added edge references fail', () => { const e = copy(); e.networks['braess-network'].edges[0].from = 'missing'; assert.throws(() => validateEpisode(e), /edges\[0\].from/); const b = copy(); b.networks['braess-network'].addedEdgeId = 'missing'; assert.throws(() => validateEpisode(b), /addedEdgeId/); });
test('bidding references must name a participant', () => { const e = JSON.parse(JSON.stringify(auction)); e.scenes[2].content.bids[0].bidderId = 'ghost'; assert.throws(() => validateEpisode(e), /bids\[0\].bidderId/); });
