export const MAX_REPAIR_ATTEMPTS = 2;
export const MAX_BRIEF_REPAIR_ATTEMPTS = 2;
export const MAX_OUTPUT_TOKEN_RETRIES = 1;
export const MAX_STRUCTURED_OUTPUT_TOKENS = 12_000;
export const MAX_VISUAL_PLAN_REPAIR_ATTEMPTS = 1;
export const MAX_VISUAL_QA_REPAIR_ATTEMPTS = 1;
