import 'dotenv/config';
import {redactFactoryV2Message,runFactoryV2,type FactoryV2Options} from '../src/factory-v2/factoryV2';

const usage='Usage: npm run factory:v2 -- --topic "..." --id episode-id [--duration 150] (--draft|--release) [--resume|--existing-artifacts] [--max-recraft-assets 3] [--allow-high-risk] [--override-qa-fail --override-reason "reason"]';
function parse(args:string[]):FactoryV2Options&{help?:boolean}{const values:Record<string,string>={};const flags=new Set<string>();for(let i=0;i<args.length;i++){const [key,inline]=args[i].split(/=(.*)/s,2);if(key==='--help')return{id:'help',mode:'draft',help:true};if(['--draft','--release','--resume','--existing-artifacts','--allow-high-risk','--override-qa-fail'].includes(key)){if(flags.has(key))throw new Error(`${key} was provided more than once.`);flags.add(key);continue;}if(!['--topic','--id','--duration','--max-recraft-assets','--override-reason'].includes(key))throw new Error(`Unknown option ${key}.\n${usage}`);const value=inline??args[++i];if(!value||value.startsWith('--'))throw new Error(`${key} requires a value.`);if(values[key])throw new Error(`${key} was provided more than once.`);values[key]=value;}
  if(!values['--id'])throw new Error(`--id is required.\n${usage}`);if(!/^[a-z0-9][a-z0-9-]{1,79}$/.test(values['--id']))throw new Error('--id must be a safe lowercase kebab-case identifier.');if(flags.has('--draft')===flags.has('--release'))throw new Error('Provide exactly one of --draft or --release.');if(!values['--topic']&&!flags.has('--resume')&&!flags.has('--existing-artifacts'))throw new Error(`--topic is required unless --resume or --existing-artifacts is used.\n${usage}`);
  const duration=values['--duration']?Number(values['--duration']):undefined;if(duration!==undefined&&(!Number.isInteger(duration)||duration<30||duration>300))throw new Error('--duration must be an integer from 30 to 300 seconds.');const max=Number(values['--max-recraft-assets']??3);if(!Number.isInteger(max)||max<0||max>3)throw new Error('--max-recraft-assets must be an integer from 0 to 3.');if(flags.has('--override-qa-fail')&&!values['--override-reason']?.trim())throw new Error('--override-qa-fail requires --override-reason.');
  return{id:values['--id'],topic:values['--topic'],durationSeconds:duration,mode:flags.has('--release')?'release':'draft',resume:flags.has('--resume'),existingArtifacts:flags.has('--existing-artifacts'),maxRecraftAssets:max,allowHighRisk:flags.has('--allow-high-risk'),overrideQaFail:flags.has('--override-qa-fail'),overrideReason:values['--override-reason']};}
async function main(){const options=parse(process.argv.slice(2));if(options.help){console.log(usage);return;}const result=await runFactoryV2(options);console.log(`Factory V2 status: ${result.status}`);}
main().catch((error:unknown)=>{console.error(redactFactoryV2Message(error));process.exitCode=1;});
