import 'dotenv/config';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {generateAssets} from '../src/assets/generation/assetGenerator';

const usage='Usage: npm run generate:assets -- --plan generated/<episode-id>/asset-plan.json [--dry-run] [--force] [--retry-failed] [--allow-high-risk]';
function parse(args:string[]) { const values:Record<string,string>={}; const flags=new Set<string>(); for(let i=0;i<args.length;i+=1){const [key,inline]=args[i].split(/=(.*)/s,2); if(key==='--help')return{help:true,values,flags}; if(['--dry-run','--force','--retry-failed','--allow-high-risk'].includes(key)){if(flags.has(key))throw new Error(`${key} was provided more than once.`);flags.add(key);continue;} if(key!=='--plan')throw new Error(`Unknown option ${key}.\n${usage}`); const value=inline??args[++i];if(!value||value.startsWith('--'))throw new Error('--plan requires a path.');if(values[key])throw new Error('--plan was provided more than once.');values[key]=value;}if(!values['--plan'])throw new Error(`--plan is required.\n${usage}`);return{help:false,values,flags}; }
async function run(){const args=parse(process.argv.slice(2));if(args.help){console.log(usage);return;}const planPath=path.resolve(args.values['--plan']);const plan=JSON.parse(await readFile(planPath,'utf8')) as unknown;const flags={force:args.flags.has('--force'),retryFailed:args.flags.has('--retry-failed'),allowHighRisk:args.flags.has('--allow-high-risk')};const preview=await generateAssets(plan,{...flags,dryRun:true});
 if(args.flags.has('--dry-run')){console.log('Asset generation dry run');console.log(`Requested unique assets: ${preview.requested}`);console.log(`Cached: ${preview.cached}`);console.log(`Generate: ${preview.generate}`);console.log(`High risk: ${preview.highRisk}`);console.log(`Budget: ${preview.requested} / ${((plan as {budget?:{hardMax?:number}}).budget?.hardMax)??'unknown'}`);console.log('Recraft calls: 0');return;}
 if(preview.generate===0)console.log('No new Recraft assets required. Recraft API calls: 0');else console.log(`About to generate ${preview.generate} Recraft assets.`);const result=await generateAssets(plan,{...flags,dryRun:false});const report=result.report!;console.log('Asset generation complete');console.log(`Requested: ${report.requestedAssetCount}`);console.log(`Generated: ${report.newGenerationCount}`);console.log(`Cache hits: ${report.cacheHitCount}`);console.log(`Reuse hits: ${report.reuseCount}`);console.log(`High-risk skipped: ${report.skippedHighRiskCount}`);console.log(`Failures: ${report.failureCount}`);console.log(`Recraft API calls: ${report.recraftCallCount}`);console.log(`Status: ${report.status}`);console.log(`Manifest: assets/generated/${report.episodeId}/asset-manifest.json`);console.log(`Preview: assets/generated/${report.episodeId}/preview.html`);for(const warning of report.warnings)console.warn(`Warning: ${warning}`);if(report.failureCount)process.exitCode=1;}
run().catch((error:unknown)=>{console.error(error instanceof Error?error.message:'Asset generation failed.');process.exitCode=1;});
