import 'dotenv/config';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {EpisodeSchema} from '../src/episode/schema';
import {normalizeEpisode} from '../src/episode/normalizeEpisode';
import {buildSceneTimeline} from '../src/engine/timeline';
import {VisualPlanSchema} from '../src/visual/schemas';
import {AssetPlanSchema} from '../src/assets/assetStrategySchema';
import {AssetGenerationManifestSchema} from '../src/assets/generation/assetGenerationSchema';
import {HybridRenderReportSchema} from '../src/composition/hybridTypes';
import {createHybridProductionContext} from '../src/composition/productionContext';
import {resolveRenderStrategies} from '../src/factory/renderStrategy';
import {renderEpisode,renderEpisodeStillFrames} from './render/episodeRenderer';

const usage='Usage: npm run render:hybrid -- --episode episodes/generated/<id>.json --visual-plan generated/<id>/visual-plan.json --asset-plan generated/<id>/asset-plan.json --manifest assets/generated/<id>/asset-manifest.json [--allow-pending-assets] [--output output/<id>-hybrid.mp4]';
function parse(args:string[]){const values:Record<string,string>={};const flags=new Set<string>();for(let i=0;i<args.length;i++){const [key,inline]=args[i].split(/=(.*)/s,2);if(key==='--help')return{help:true,values,flags};if(key==='--allow-pending-assets'){if(flags.has(key))throw new Error(`${key} was provided more than once.`);flags.add(key);continue;}if(!['--episode','--visual-plan','--asset-plan','--manifest','--output'].includes(key))throw new Error(`Unknown option ${key}.\n${usage}`);const value=inline??args[++i];if(!value||value.startsWith('--'))throw new Error(`${key} requires a value.`);if(values[key])throw new Error(`${key} was provided more than once.`);values[key]=value;}for(const key of ['--episode','--visual-plan','--asset-plan','--manifest'])if(!values[key])throw new Error(`${key} is required.\n${usage}`);return{help:false,values,flags};}
async function json(file:string){return JSON.parse(await readFile(path.resolve(file),'utf8')) as unknown;}
function framesForQa(episode:ReturnType<typeof normalizeEpisode>,signatureId:string){const timeline=buildSceneTimeline(episode.scenes);const length=episode.durationInFrames;const frames=new Set<number>();for(let index=0;index<10;index++)frames.add(Math.min(length-1,Math.floor((length-1)*index/9)));const signature=timeline.find((item)=>item.spec.id===signatureId);if(signature)frames.add(Math.floor(signature.startFrame+signature.spec.durationInFrames/2));for(const entry of timeline){if(entry.spec.type==='diagram'||entry.spec.type==='simulation'||entry.spec.type==='comparison')frames.add(Math.floor(entry.startFrame+entry.spec.durationInFrames/2));}let result=[...frames].sort((a,b)=>a-b);while(result.length>10)result.splice(result.length-2,1);while(result.length<8)result.push(Math.floor((length-1)*(result.length+1)/10));return [...new Set(result)].sort((a,b)=>a-b).slice(0,10);}
async function writeReport(file:string,report:unknown){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,`${JSON.stringify(HybridRenderReportSchema.parse(report),null,2)}\n`,'utf8');}
async function main(){const args=parse(process.argv.slice(2));if(args.help){console.log(usage);return;}const episodePath=path.resolve(args.values['--episode']);const episode=EpisodeSchema.parse(await json(episodePath));const visualPlan=VisualPlanSchema.parse(await json(args.values['--visual-plan']));const assetPlan=AssetPlanSchema.parse(await json(args.values['--asset-plan']));const manifest=AssetGenerationManifestSchema.parse(await json(args.values['--manifest']));const allowPendingAssets=args.flags.has('--allow-pending-assets');const root=process.cwd();const context=await createHybridProductionContext({root,episode,visualPlan,assetPlan,manifest,reviewFile:path.join(root,'assets','generated',episode.id,'asset-review.json'),allowPendingAssets});
  const generatedDirectory=path.resolve(root,'generated',episode.id);await mkdir(generatedDirectory,{recursive:true});const snapshotPath=path.join(generatedDirectory,'hybrid-render-input.json');await writeFile(snapshotPath,`${JSON.stringify(context.snapshot,null,2)}\n`,'utf8');const output=path.resolve(args.values['--output']??path.join('output',`${episode.id}-hybrid${allowPendingAssets?'-draft':''}.mp4`));const visual=resolveRenderStrategies(episode,visualPlan);const hybridProps={resolvedHybridAssets:context.resolution.sceneAssets,hybridFallbacks:Object.fromEntries(context.scenes.map((scene)=>[scene.sceneId,scene.fallbacks])),hybridLayouts:Object.fromEntries(context.scenes.map((scene)=>[scene.sceneId,scene.layout])),signatureSceneIds:[context.signatureSceneId]};const base={...context.reportBase,outputPath:path.relative(root,output).replace(/\\/g,'/'),renderStatus:allowPendingAssets&&context.reportBase.pendingAssetCount>0?'DRAFT — UNREVIEWED ASSETS' as const:'rendered' as const};
  const reportPath=path.join(generatedDirectory,'hybrid-render-report.json');try{await renderEpisode(episodePath,{outputLocation:output,visualStrategies:visual.strategies,...hybridProps});const normalized=normalizeEpisode(episode);const frames=framesForQa(normalized,context.signatureSceneId);const qaHybrid=path.resolve(root,'qa',episode.id,'hybrid');const comparePhase1=path.resolve(root,'qa',episode.id,'comparison','phase1');const compareHybrid=path.resolve(root,'qa',episode.id,'comparison','hybrid');await renderEpisodeStillFrames({file:episodePath,outputDirectory:qaHybrid,frames,visualStrategies:visual.strategies,hybridProps});await renderEpisodeStillFrames({file:episodePath,outputDirectory:comparePhase1,frames,visualStrategies:visual.strategies});await renderEpisodeStillFrames({file:episodePath,outputDirectory:compareHybrid,frames,visualStrategies:visual.strategies,hybridProps});const report=HybridRenderReportSchema.parse({...base,warnings:[...base.warnings,...visual.visualFallbacks.map((warning)=>`Visual fallback: ${warning}`),`Rendered ${frames.length} matched QA still frames for Phase 1 and Phase 2 comparison.`]});await writeReport(reportPath,report);console.log('Phase 2 Hybrid Scene Composer');console.log(`Episode: ${episode.id}`);console.log(`Review mode: ${allowPendingAssets?'draft (pending assets allowed)':'safe (pending assets fall back)'}`);console.log(`Scenes: ${report.sceneCount} | procedural ${report.proceduralSceneCount} | hybrid ${report.hybridSceneCount} | recraft ${report.recraftSceneCount} | reuse ${report.reuseSceneCount}`);console.log(`Assets: approved ${report.approvedAssetCount} | pending ${report.pendingAssetCount} | rejected ${report.rejectedAssetCount} | staged ${report.stagedAssetCount}`);console.log(`Fallbacks: ${report.fallbackCount} | signature rendered: ${report.signatureMomentRendered}`);console.log(`Illustration-dominant ratio: ${report.illustrationDominantSceneRatio.toFixed(3)}`);console.log(`Render status: ${report.renderStatus}`);console.log(`MP4: ${output}`);console.log(`Input snapshot: ${snapshotPath}`);console.log(`Report: ${reportPath}`);console.log(`QA stills: ${qaHybrid}`);
  }catch(error){const failed=HybridRenderReportSchema.parse({...base,renderStatus:'failed',warnings:[...base.warnings,error instanceof Error?error.message:'Hybrid rendering failed.']});await writeReport(reportPath,failed);throw error;}}
main().catch((error:unknown)=>{console.error(error instanceof Error?error.message:'Hybrid rendering failed.');process.exitCode=1;});
