import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {AssetGenerationManifestSchema} from '../src/assets/generation/assetGenerationSchema';
import {AssetReviewStateSchema,type AssetReviewDecision} from '../src/composition/hybridTypes';

const usage='Usage: npm run review:asset -- --episode ID --asset ID (--approve|--reject|--pending) [--note TEXT]';
function parse(args:string[]){const values:Record<string,string>={};const decisions:AssetReviewDecision[]=[];for(let i=0;i<args.length;i++){const key=args[i];if(key==='--approve'||key==='--reject'||key==='--pending'){decisions.push(({ '--approve':'approved','--reject':'rejected','--pending':'pending'} as const)[key]);continue;}if(!['--episode','--asset','--note'].includes(key))throw new Error(`Unknown option ${key}.\n${usage}`);const value=args[++i];if(!value||value.startsWith('--'))throw new Error(`${key} requires a value.`);if(values[key])throw new Error(`${key} may only be provided once.`);values[key]=value;}if(!values['--episode']||!values['--asset'])throw new Error(`Both --episode and --asset are required.\n${usage}`);if(decisions.length!==1)throw new Error('Provide exactly one of --approve, --reject, or --pending.');return{episode:values['--episode'],asset:values['--asset'],note:values['--note']??'',decision:decisions[0]};}
async function main(){const options=parse(process.argv.slice(2));if(!/^[a-z0-9][a-z0-9-]{1,79}$/.test(options.episode)||!/^[a-z0-9][a-z0-9-]{1,79}$/.test(options.asset))throw new Error('Episode and asset IDs must be safe lowercase identifiers.');const manifestPath=path.resolve('assets/generated',options.episode,'asset-manifest.json');const manifest=AssetGenerationManifestSchema.parse(JSON.parse(await readFile(manifestPath,'utf8')));if(manifest.episodeId!==options.episode||!manifest.assets.some((asset)=>asset.id===options.asset))throw new Error('The requested asset does not exist in this episode manifest.');const reviewPath=path.resolve('assets/generated',options.episode,'asset-review.json');let state={episodeId:options.episode,assets:[] as {assetId:string;decision:AssetReviewDecision;notes:string;reviewedAt:string}[]};try{state=AssetReviewStateSchema.parse(JSON.parse(await readFile(reviewPath,'utf8')));}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}const timestamp=new Date().toISOString();const found=state.assets.find((entry)=>entry.assetId===options.asset);if(found){found.decision=options.decision;found.notes=options.note;found.reviewedAt=timestamp;}else state.assets.push({assetId:options.asset,decision:options.decision,notes:options.note,reviewedAt:timestamp});state.assets.sort((a,b)=>a.assetId.localeCompare(b.assetId));const parsed=AssetReviewStateSchema.parse(state);await mkdir(path.dirname(reviewPath),{recursive:true});await writeFile(reviewPath,`${JSON.stringify(parsed,null,2)}\n`,'utf8');console.log(`Asset ${options.asset}: ${options.decision}`);console.log(`Review state: ${path.relative(process.cwd(),reviewPath)}`);}
main().catch((error:unknown)=>{console.error(error instanceof Error?error.message:'Asset review update failed.');process.exitCode=1;});
